"""add quiz folder

Revision ID: 03382b47e85d
Revises: 3f35efbd3040
Create Date: 2026-01-08 23:03:29.572330

"""
from __future__ import annotations



from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '03382b47e85d'
down_revision = '3f35efbd3040'
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('quiz_folders',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('notebook_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'notebook_id', 'name', name='uq_quiz_folders_user_nb_name')
        )
        op.create_index('idx_quiz_folders_user_nb', 'quiz_folders', ['user_id', 'notebook_id'], unique=False)
        op.create_table('quiz_folder_items',
        sa.Column('folder_id', sa.UUID(), nullable=False),
        sa.Column('question_id', sa.UUID(), nullable=False),
        sa.Column('seq', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['folder_id'], ['quiz_folders.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('folder_id', 'question_id')
        )
        op.create_index('idx_quiz_folder_items_folder', 'quiz_folder_items', ['folder_id'], unique=False)
        op.create_index('idx_quiz_folder_items_question', 'quiz_folder_items', ['question_id'], unique=False)
        op.add_column('quiz_questions', sa.Column('explaination', sa.Text(), nullable=True))
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_column('quiz_questions', 'explaination')
        op.drop_index('idx_quiz_folder_items_question', table_name='quiz_folder_items')
        op.drop_index('idx_quiz_folder_items_folder', table_name='quiz_folder_items')
        op.drop_table('quiz_folder_items')
        op.drop_index('idx_quiz_folders_user_nb', table_name='quiz_folders')
        op.drop_table('quiz_folders')
        # ### end Alembic commands ###
