"""add quiz_attempts table

Revision ID: 04b67afe490d
Revises: 03382b47e85d
Create Date: 2026-01-10 11:52:18.936973

"""
from __future__ import annotations



from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '04b67afe490d'
down_revision = '03382b47e85d'
branch_labels = None
depends_on = None

from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('quiz_attempts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('folder_id', sa.UUID(), nullable=False),
        sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('total_questions', sa.Integer(), nullable=False),
        sa.Column('correct_count', sa.Integer(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['folder_id'], ['quiz_folders.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('folder_id')
        )
        op.create_index('idx_quiz_attempts_folder', 'quiz_attempts', ['folder_id'], unique=False)
        op.create_index('idx_quiz_attempts_user', 'quiz_attempts', ['user_id'], unique=False)
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_index('idx_quiz_attempts_user', table_name='quiz_attempts')
        op.drop_index('idx_quiz_attempts_folder', table_name='quiz_attempts')
        op.drop_table('quiz_attempts')
        # ### end Alembic commands ###
