"""update the enum type

Revision ID: 0ef8f788d9c4
Revises: 2d48c8f8158e
Create Date: 2025-11-20 00:08:58.984386

"""
from __future__ import annotations



from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0ef8f788d9c4'
down_revision = '2d48c8f8158e'
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        pass
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        pass
        # ### end Alembic commands ###
