"""Update the relationship between attachment and transcription

Revision ID: 1b42a0d9a294
Revises: 0b4b60edd8f0
Create Date: 2025-11-19 20:21:22.441710

"""
from __future__ import annotations



from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1b42a0d9a294'
down_revision = '0b4b60edd8f0'
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        pass
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        pass
        # ### end Alembic commands ###
