"""Add summary to the attachment

Revision ID: 1c1b74155a7b
Revises: 4922e15c3899
Create Date: 2025-10-30 23:16:32.942786

"""
from __future__ import annotations



from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1c1b74155a7b'
down_revision = '4922e15c3899'
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_constraint('users_email_key', 'users', type_='unique')
        op.drop_index('ix_users_email', table_name='users')
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_index(op.f('ix_users_email'), table_name='users')
        op.create_index('ix_users_email', 'users', ['email'], unique=False)
        op.create_unique_constraint('users_email_key', 'users', ['email'])
        # ### end Alembic commands ###
