"""remove description from the mind map

Revision ID: 3f35efbd3040
Revises: 7b2719730c16
Create Date: 2026-01-04 20:34:31.161613

"""
from __future__ import annotations



from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3f35efbd3040'
down_revision = '7b2719730c16'
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_column('mindmaps', 'description')
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('mindmaps', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        # ### end Alembic commands ###
