"""ADD flash card, folder and quiz. update the notebook and attachment

Revision ID: 8f1dd654eb5d
Revises: 1c1b74155a7b
Create Date: 2025-11-19 00:38:23.901122

"""
from __future__ import annotations



from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8f1dd654eb5d'
down_revision = '1c1b74155a7b'
branch_labels = None
depends_on = None

from sqlalchemy.dialects import postgresql

attachment_transcription_status_enum = postgresql.ENUM(
    'NONE',
    'PENDING',
    'COMPLETED',
    'FAILED',
    name='attachment_transcription_status',
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('notebook_folders',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('color', sa.String(length=32), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'name', name='uq_notebook_folders_user_name')
        )
        op.create_index('idx_notebook_folders_user', 'notebook_folders', ['user_id'], unique=False)
        op.create_table('flashcard_folders',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('notebook_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'notebook_id', 'name', name='uq_flashcard_folders_user_nb_name')
        )
        op.create_index('idx_flashcard_folders_user_nb', 'flashcard_folders', ['user_id', 'notebook_id'], unique=False)
        op.create_table('flashcards',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('notebook_id', sa.UUID(), nullable=False),
        sa.Column('question', sa.Text(), nullable=False),
        sa.Column('answer', sa.Text(), nullable=False),
        sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_flashcards_user_nb', 'flashcards', ['user_id', 'notebook_id'], unique=False)
        op.create_table('mindmaps',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('notebook_id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_mindmaps_user_nb', 'mindmaps', ['user_id', 'notebook_id'], unique=False)
        op.create_table('notebook_folder_items',
        sa.Column('folder_id', sa.UUID(), nullable=False),
        sa.Column('notebook_id', sa.UUID(), nullable=False),
        sa.Column('seq', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['folder_id'], ['notebook_folders.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('folder_id', 'notebook_id')
        )
        op.create_index('idx_notebook_folder_items_folder', 'notebook_folder_items', ['folder_id'], unique=False)
        op.create_index('idx_notebook_folder_items_notebook', 'notebook_folder_items', ['notebook_id'], unique=False)
        op.create_table('quiz_questions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('notebook_id', sa.UUID(), nullable=False),
        sa.Column('question', sa.Text(), nullable=False),
        sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('correct_index', sa.Integer(), nullable=False),
        sa.Column('hint', sa.Text(), nullable=True),
        sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_favorite', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_quiz_questions_user_nb', 'quiz_questions', ['user_id', 'notebook_id'], unique=False)
        op.create_table('flashcard_folder_items',
        sa.Column('folder_id', sa.UUID(), nullable=False),
        sa.Column('flashcard_id', sa.UUID(), nullable=False),
        sa.Column('seq', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['folder_id'], ['flashcard_folders.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('folder_id', 'flashcard_id')
        )
        op.create_index('idx_flashcard_folder_items_flashcard', 'flashcard_folder_items', ['flashcard_id'], unique=False)
        op.create_index('idx_flashcard_folder_items_folder', 'flashcard_folder_items', ['folder_id'], unique=False)
        op.drop_table('note_tags')
        op.drop_table('tags')
        op.add_column('attachments', sa.Column('filename', sa.String(length=255), nullable=True))
        op.add_column('attachments', sa.Column('s3_object_key', sa.String(length=512), nullable=True))
        op.add_column('attachments', sa.Column('s3_url', sa.String(length=512), nullable=True))
        op.add_column('attachments', sa.Column('external_url', sa.String(length=512), nullable=True))
        op.add_column('attachments', sa.Column('openai_file_id', sa.String(length=255), nullable=True))
        op.add_column('attachments', sa.Column('openai_file_purpose', sa.String(length=64), nullable=True))
        op.add_column('attachments', sa.Column('enable_file_search', sa.Boolean(), server_default='true', nullable=False))
        attachment_transcription_status_enum.create(op.get_bind(), checkfirst=True)
        op.add_column(
            'attachments',
            sa.Column(
                'transcription_status',
                attachment_transcription_status_enum,
                server_default=sa.text("'NONE'::attachment_transcription_status"),
                nullable=False,
            ),
        )
        op.add_column('attachments', sa.Column('transcription_lang', sa.String(length=32), nullable=True))
        op.add_column('attachments', sa.Column('transcription_duration_sec', sa.Integer(), nullable=True))
        op.add_column('attachments', sa.Column('last_transcription_session_id', sa.UUID(), nullable=True))
        op.add_column('attachments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        op.create_index('idx_attachments_openai_file_id', 'attachments', ['openai_file_id'], unique=False)
        op.create_foreign_key(None, 'attachments', 'transcription_sessions', ['last_transcription_session_id'], ['id'], ondelete='SET NULL')
        op.drop_column('attachments', 'object_key')
        op.add_column('notebooks', sa.Column('color', sa.String(length=32), nullable=True))
        op.add_column('notebooks', sa.Column('openai_vector_store_id', sa.String(length=255), nullable=True))
        op.add_column('notebooks', sa.Column('vector_store_expires_at', sa.DateTime(timezone=True), nullable=True))
        op.alter_column('transcription_sessions', 'attachment_id',
                   existing_type=sa.UUID(),
                   nullable=False)
        op.drop_constraint('transcription_sessions_attachment_id_fkey', 'transcription_sessions', type_='foreignkey')
        op.create_foreign_key(None, 'transcription_sessions', 'attachments', ['attachment_id'], ['id'], ondelete='CASCADE')
        op.drop_column('transcription_sessions', 'engine')
        op.drop_column('transcription_sessions', 'model')
        op.drop_column('transcription_sessions', 'session_uid')
        op.drop_column('transcription_sessions', 'confidence')
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('transcription_sessions', sa.Column('confidence', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
        op.add_column('transcription_sessions', sa.Column('session_uid', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        op.add_column('transcription_sessions', sa.Column('model', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        op.add_column('transcription_sessions', sa.Column('engine', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        op.drop_constraint(None, 'transcription_sessions', type_='foreignkey')
        op.create_foreign_key('transcription_sessions_attachment_id_fkey', 'transcription_sessions', 'attachments', ['attachment_id'], ['id'], ondelete='SET NULL')
        op.alter_column('transcription_sessions', 'attachment_id',
                   existing_type=sa.UUID(),
                   nullable=True)
        op.drop_column('notebooks', 'vector_store_expires_at')
        op.drop_column('notebooks', 'openai_vector_store_id')
        op.drop_column('notebooks', 'color')
        op.add_column('attachments', sa.Column('object_key', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
        op.drop_constraint(None, 'attachments', type_='foreignkey')
        op.drop_index('idx_attachments_openai_file_id', table_name='attachments')
        op.drop_column('attachments', 'updated_at')
        op.drop_column('attachments', 'last_transcription_session_id')
        op.drop_column('attachments', 'transcription_duration_sec')
        op.drop_column('attachments', 'transcription_lang')
        op.drop_column('attachments', 'transcription_status')
        attachment_transcription_status_enum.drop(op.get_bind(), checkfirst=True)
        op.drop_column('attachments', 'enable_file_search')
        op.drop_column('attachments', 'openai_file_purpose')
        op.drop_column('attachments', 'openai_file_id')
        op.drop_column('attachments', 'external_url')
        op.drop_column('attachments', 's3_url')
        op.drop_column('attachments', 's3_object_key')
        op.drop_column('attachments', 'filename')
        op.create_table('tags',
        sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tags_user_id_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='tags_pkey'),
        sa.UniqueConstraint('user_id', 'name', name='uq_tags_user_name')
        )
        op.create_table('note_tags',
        sa.Column('notebook_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], name='note_tags_notebook_id_fkey', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='note_tags_tag_id_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('notebook_id', 'tag_id', name='note_tags_pkey')
        )
        op.drop_index('idx_flashcard_folder_items_folder', table_name='flashcard_folder_items')
        op.drop_index('idx_flashcard_folder_items_flashcard', table_name='flashcard_folder_items')
        op.drop_table('flashcard_folder_items')
        op.drop_index('idx_quiz_questions_user_nb', table_name='quiz_questions')
        op.drop_table('quiz_questions')
        op.drop_index('idx_notebook_folder_items_notebook', table_name='notebook_folder_items')
        op.drop_index('idx_notebook_folder_items_folder', table_name='notebook_folder_items')
        op.drop_table('notebook_folder_items')
        op.drop_index('idx_mindmaps_user_nb', table_name='mindmaps')
        op.drop_table('mindmaps')
        op.drop_index('idx_flashcards_user_nb', table_name='flashcards')
        op.drop_table('flashcards')
        op.drop_index('idx_flashcard_folders_user_nb', table_name='flashcard_folders')
        op.drop_table('flashcard_folders')
        op.drop_index('idx_notebook_folders_user', table_name='notebook_folders')
        op.drop_table('notebook_folders')
        # ### end Alembic commands ###
