// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    AttachmentDocViewer: typeof import('./src/components/note/AttachmentDocViewer.vue')['default']
    AttachmentPdfViewer: typeof import('./src/components/note/AttachmentPdfViewer.vue')['default']
    AuthPopup: typeof import('./src/components/AuthPopup.vue')['default']
    ConfirmModal: typeof import('./src/components/common/ConfirmModal.vue')['default']
    MarkdownRenderer: typeof import('./src/components/MarkdownRenderer.vue')['default']
    Message: typeof import('./src/components/message.vue')['default']
    NotebookNotesList: typeof import('./src/components/note/NotebookNotesList.vue')['default']
    NoteChatPanel: typeof import('./src/components/note/NoteChatPanel.vue')['default']
    NoteEditorPanel: typeof import('./src/components/note/NoteEditorPanel.vue')['default']
    NoteFlashcardsPanel: typeof import('./src/components/note/NoteFlashcardsPanel.vue')['default']
    NoteMaterialsPanel: typeof import('./src/components/note/NoteMaterialsPanel.vue')['default']
    NoteMindMapPanel: typeof import('./src/components/note/NoteMindMapPanel.vue')['default']
    NoteQuizPanel: typeof import('./src/components/note/NoteQuizPanel.vue')['default']
    NoteRecordingPanel: typeof import('./src/components/note/NoteRecordingPanel.vue')['default']
    NoteTranscriptionPanel: typeof import('./src/components/note/NoteTranscriptionPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/setting.vue')['default']
  }
}
